\version "2.22.1"
% automatically converted by musicxml2ly from /Users/rupertrebentisch/scanscore2lilypond/scanscore2lilypond/tests/test_files/Pleyel_Presto_I_step1.xml
\pointAndClickOff

\header {
    encodingsoftware =  "MusicXML Library v3"
    }

#(set-global-staff-size 17.142857142857146)
\paper {
    
    paper-width = 21.0\cm
    paper-height = 29.7\cm
    top-margin = 1.5\cm
    bottom-margin = 1.5\cm
    left-margin = 1.5\cm
    right-margin = 1.5\cm
    indent = 1.6153846153846154\cm
    }
\layout {
    \context { \Score
        autoBeaming = ##f
        }
    }
PartPOneVoiceOne =  \relative a' {
    \repeat volta 2 {
        \clef "alto" \time 1/8 \key f \major \break | % 1
        \tempo "" 4=120 a8 ^. _\f | % 2
        \time 2/4  \bar "|"
        f8 ^. [ e8 ^. d8 ^. cis8 ^. ] \bar "|"
        d4. e8 ^. \bar "|"
        f8 ^. [ e8 ^. d8 ^. c8 ^. ] \bar "|"
        d4. e8 ^. \bar "|"
        f8 ^. [ d8 ^. f8 ^. g8 ^. ] \bar "|"
        a8 ^. [ f8 ^. a8 ^. bes8 ^. ] \bar "|"
        bes8 ( [ a8 ) g8 ^. f8 ^. ] \bar "|"
        e4 r8 a8 ^. \bar "|"
        \break | \barNumberCheck #10
        f8 ^. [ e8 ^. d8 ^. cis8 ^. ] \bar "|"
        d4. e8 ^. \bar "|"
        f8 ^. [ e8 ^. d8 ^. c8 ^. ] \bar "|"
        d4. e8 ^. \bar "|"
        f8 ^. [ d8 ^. f8 ^. g8 ^. ] \bar "|"
        a8 ^. [ f8 ^. a8 ^. bes8 ^. ] \bar "|"
        a8 [ g8 f8 ^. e8 ^. ] \bar "|"
        d4 r8 e8 ^. _\p \bar "|"
        \break | % 18
        f8 ( [ e8 f8 g8 ) ] \bar "|"
        e4 ( r8 f8 ) ^. \bar "|"
        \acciaccatura { a8 ( } g8 ) [ f8 g8 a8 ] \bar "|"
        f4 r8 g8 ^. \bar "|"
        \acciaccatura { bes8 } a8 ( [ g8 a8 bes8 ) ] \bar "|"
        g4 r8 a8 ^. \bar "|"
        \acciaccatura { c8 _. } bes8 ( [ a8 bes8 c8 ) ] \bar "|"
        a8 ^. [ cis8 ( _\f d8 a8 ) ] \bar "|"
        \break | % 26
        r4 c4 _. \bar "|"
        f,8 ^. [ a8 ( bes8 f8 ) ] \bar "|"
        e8 ( [ gis8 ) a8 e8 ^. ] \bar "|"
        d8 ^. [ fis8 ( g8 d8 ) ] \bar "|"
        c8 ( [ e8 ) f8 ^. c8 ^. ] \bar "|"
        bes8 ^. [ g'8 ^. a,8 ^. f'8 ^. ] \bar "|"
        bes,8 ^. [ g'8 ^. a,8 ^. f'8 ^. ] \bar "|"
        \break | % 33
        d8 ( [ fis8 ) g8 ^. a8 ^. ] \bar "|"
        bes8 ( [ c8 ) d8 ^. f,8 ^. ] \bar "|"
        e4 g4 ~ \bar "|"
        g4 c,,4 \bar "|"
        f4 f'4 ~ _\f \bar "|"
        f4 e4 \bar "|"
        e4 d4 \bar "|"
        d4 c4 \bar "|"
        bes4 bes4 \bar "|"
        \break | % 42
        bes4 a4 _. \bar "|"
        g8 ( [ bes8 ) ^. d8 ^. fis8 ^. ] \bar "|"
        g8 ( [ bes8 ) d8 ^. f,8 ^. ] \bar "|"
        e4 <c' e, g, c,>4 \bar "|"
        <c e, g, c,>4 r8 c8 ^. _\p \bar "|"
        a8 [ g8 ^. f8 ^. e8 ^. ] \bar "|"
        f4. g8 ^. \bar "|"
        a8 ^. [ g8 ^. f8 ^. e8 ] \bar "|"
        f4. g8 ^. \bar "|"
        \break | % 51
        a8 ^. [ _\f f8 ^. a8 ^. bes8 ^. ] \bar "|"
        c8 ^. [ a8 ^. c8 ^. d8 ^. ] \bar "|"
        e8 ^. [ c8 ^. e8 ^. f8 ] \bar "|"
        g8 ^. [ e8 ^. c8 ^. bes8 ^. ] \bar "|"
        a8 ^. [ f'8 ^. g,8 ^. e'8 ^. ] \bar "|"
        f,8 ^. [ d'8 ^. _\< e,8 ^. c'8 ^. ] \bar "|"
        d,8 ^. [ _\! _\< _\< _\< _\< _\< _\< _\< bes'8 ^. _\< c,8 ^. a'8
        ^. ] \bar "|"
        bes,8 ^. [ _\! _\< _\< _\< _\< _\< _\< _\< bes'8 a,8 ^. f'8 ^. ]
        \bar "|"
        \break | % 59
        d8 ^. [ d'8 ^. bes8 ^. g8 ^. ] \bar "|"
        a8 ^. [ c8 ^. e,8 ^. g8 ^. ] \bar "|"
        f4 r8 f8 ^. _\p \bar "|"
        e8 ^. [ c'8 ( b8 bes8 ) ] \bar "|"
        a4 r8 f8 ^. \bar "|"
        e8 ^. [ c'8 ( b8 bes8 ) ] \bar "|"
        a8 ^. [ d8 ( _\f c8 c8 ) ] \bar "|"
        bes8 ^. [ c8 ^. a8 ^. bes8 ^. ] \bar "|"
        \break | % 67
        g8 ^. [ a8 ^. f8 ^. g8 ^. ] \bar "|"
        e8 ^. [ d'8 ^. c8 ^. f,8 ^. ] \bar "|"
        e8 ^. [ d'8 ^. c8 ^. f,8 ^. ] \bar "|"
        e8 ^. [ d'8 ^. c8 ^. f,8 ^. ] \bar "|"
        e8 ^. [ d'8 ^. c8 ^. f,8 ^. ] \bar "|"
        d8 ^. [ bes'8 ^. a8 ^. g8 ^. ] \bar "|"
        <f a,>4 <e g, c,>4 \bar "|"
        <f a, c,>8 a,8 ( [ _\p bes8 bes8 ) ] \bar "|"
        \break | % 75
        c8 _. [ c,8 ( d8 e8 ) ] \bar "|"
        f8 _. [ a8 ( bes8 b8 ) ] \bar "|"
        c8 _. [ c,8 ( d8 e8 ) ] \bar "|"
        f4 r8 f'8 ^. \bar "|"
        g8 ^. [ e8 ^. f8 ^. d8 ^. ] \bar "|"
        e8 ^. [ c8 ^. d8 ^. bes8 ^. ] \bar "|"
        c8 _. [ bes8 _. _\f a8 _. ] r8 \bar "|"
        c8 _. [ bes8 _. a8 _. ] r8 \bar "|"
        \break | % 83
        c8 _. [ bes8 _. a8 _. ] r8 \bar "|"
        c8 _. [ bes8 _. a8 _. ] r8 \bar "|"
        bes8 _. [ g8 _. a8 _. bes8 _. ] \bar "|"
        c8 _. [ c8 _. c,8 _. c8 _. ] \bar "|"
        f8 ^. [ c''8 bes8 a8 ] \bar "|"
        a8 ^. [ bes8 ( a8 g8 ) ] \bar "|"
        a8 ^. [ a8 ( g8 f8 ) ] \bar "|"
        e8 ^. [ g8 ( f8 e8 ) ] \bar "|"
        \break | % 91
        f4 <f a, c,>4 | % 92
        \time 3/8  \bar "|"
        <f a, c,>4 r8 }
    \time 2/4  \bar "|"
    a8 ^. | % 94
    f8 ^. [ e8 ^. d8 ^. cis8 ^. ] \bar "|"
    d4 r8 d'8 ^. \bar "|"
    bes8 ^. [ a8 ^. g8 ^. fis8 ^. ] \bar "|"
    g4 r8 g8 ^. \bar "|"
    e8 ^. [ d8 ^. c8 ^. bes8 ^. ] \bar "|"
    c4 r8 c'8 ^. \bar "|"
    \break | \barNumberCheck #100
    a8 ^. [ g8 ^. f8 ^. e8 ^. ] \bar "|"
    f4 r8 a8 ^. _\f \bar "|"
    bes8 ^. [ c8 ^. d8 ^. bes8 ^. ] \bar "|"
    c8 ^. [ d8 ^. es8 ^. c8 ^. ] \bar "|"
    d4 r8 f8 ^. _\p \bar "|"
    d8 ^. [ c8 ^. bes8 ^. a8 ^. ] \bar "|"
    bes4. c8 ^. \bar "|"
    d8 ^. [ c8 ^. bes8 ^. a8 ^. ] \bar "|"
    \pageBreak | % 108
    bes4 r8 c,8 ^. _\f \bar "|"
    d8 ^. [ bes8 ^. d8 ^. es8 ^. ] \bar "|"
    f8 ^. [ es8 ^. d8 ^. c8 ^. ] \bar "|"
    b8 ^. [ d'8 ^. b8 ^. g8 ] \bar "|"
    c4 r8 g'8 ^. _\p \bar "|"
    es8 ^. [ d8 ^. c8 ^. b8 ^. ] \bar "|"
    c4 r8 g'8 ^. _\f \bar "|"
    es8 ^. [ d8 ^. c8 ^. f8 ^. ] \bar "|"
    \break | % 116
    d8 ^. [ c8 ^. bes8 ^. es8 ^. ] \bar "|"
    c8 ^. [ bes8 ^. a8 ^. d8 ^. ] \bar "|"
    bes8 ^. [ a8 ^. g8 ^. d'8 ^. ] \bar "|"
    cis8 ^. [ g8 ^. e8 ^. d'8 ^. ] \bar "|"
    cis8 ^. [ g8 ^. e8 ^. d'8 ^. ] _\f \bar "|"
    cis8 ^. [ d8 ^. _\< cis8 ^. d8 ^. ] \bar "|"
    cis8 ^. [ _\! _\< _\< _\< _\< _\< _\< _\< g8 ^. e8 ^. c'8 ^. ] \bar
    "|"
    \break | % 123
    b8 ^. [ f8 ^. d8 ^. c'8 ^. ] \bar "|"
    b8 ^. [ f8 ^. d8 ^. c'8 ^. ] \bar "|"
    b8 ^. [ _\< c8 ^. b8 ^. c8 ^. ] \bar "|"
    b8 ^. [ _\! _\< _\< _\< _\< _\< _\< _\< f8 ^. d8 ^. bes'8 ^. ] \bar
    "|"
    a8 ^. [ bes8 ^. a8 ^. g8 ^. ] \bar "|"
    f8 ^. [ g8 ^. f8 ^. e8 ^. ] \bar "|"
    d8 ^. d'4 bes8 ~ \bar "|"
    bes8 a4 ( gis8 ) ^. \bar "|"
    \break | % 131
    a8 ^. [ a,8 ^. cis8 ^. e8 ^. ] \bar "|"
    a4 r8 a8 ^. _\p \bar "|"
    f8 ^. [ e8 ^. d8 ^. cis8 ^. ] \bar "|"
    d4. e8 ^. \bar "|"
    f8 ^. [ e8 ^. d8 ^. cis8 ^. ] \bar "|"
    d4. e8 ^. _\< \bar "|"
    f8 ^. [ _\! _\f _\< _\< _\< _\< _\< _\< _\< d8 ^. f8 ^. g8 ^. ] \bar
    "|"
    a8 ^. [ f8 ^. a8 ^. bes8 ^. ] \bar "|"
    \break | % 139
    bes8 ^. [ a8 ^. g8 ^. f8 ^. ] \bar "|"
    e4 r4 \bar "|"
    r4 r8 a,8 _. _\p \bar "|"
    f8 _. [ e8 _. d8 _. cis8 _. ] \bar "|"
    d4. e8 _. | % 144
    f8 _. [ e8 _. d8 _. cis8 _. ] \bar "|"
    d4. e8 _. | % 146
    f8 _. [ d8 _. f8 _. g8 _. ] \bar "|"
    \break | % 147
    f8 _. [ g8 _. a8 _. a8 _. ] \bar "|"
    d,4 r8 e'8 ^. _\p \bar "|"
    \acciaccatura { g8 ( _. } f8 ) [ _\< _\< _\< _\< _\< _\< _\< _\< e8
    f8 g8 ] \bar "|"
    e4 r8 f8 ^. \bar "|"
    \acciaccatura { a8 ( _. } g8 ) [ f8 g8 a8 ] \bar "|"
    f4 r8 a8 ^. \bar "|"
    \acciaccatura { e'8 ( _. } d8 ) [ cis8 d8 e8 ] \bar "|"
    cis4 r8 d8 ^. \bar "|"
    \break | % 155
    e8 ( [ d8 e8 f8 ) ] \bar "|"
    d4 d4 ~ _\f \bar "|"
    d4 cis4 \bar "|"
    c4 b4 \bar "|"
    bes4 a4 \bar "|"
    g4 f4 \bar "|"
    e4 d4 \bar "|"
    cis8 ( [ e8 ) a8 ^. cis8 ^. ] \bar "|"
    e8 ( [ cis8 ) a8 ^. g8 ^. ] \bar "|"
    \break | % 164
    f8 ( [ a8 ) bes8 ^. f8 ^. ] \bar "|"
    e8 ( [ gis8 ) a8 ^. e8 ^. ] \bar "|"
    d8 ( [ fis8 ) g8 ^. d8 ^. ] \bar "|"
    c8 [ e8 f8 ^. c8 ^. ] \bar "|"
    bes8 ( [ f'8 ) e8 ^. d8 ^. ] \bar "|"
    cis8 ^. [ bes'8 ( a8 g8 ) ] | \barNumberCheck #170
    fis8 ^. [ es'8 ( d8 c8 ) ] \bar "|"
    \break | % 171
    bes8 ^. [ g8 ^. e8 ^. _\< d8 ^. ] \bar "|"
    cis8 _. [ _\! _\< _\< _\< _\< _\< _\< _\< e8 _. a,8 _. g8 _. ] \bar
    "|"
    f8 _. [ a8 _. d8 _. f,8 _. ] \bar "|"
    e8 _. [ d'8 _. e,8 _. cis'8 _. ] \bar "|"
    <d a d,>4 r8 d8 ^. \bar "|"
    cis8 ^. [ a'8 ( gis8 g8 ) ] \bar "|"
    f4 r8 d8 ^. \bar "|"
    cis8 ^. [ a'8 ( gis8 g8 ) ] \bar "|"
    \break | % 179
    f8 ^. [ d'8 ( _\f cis8 c8 ) ] \bar "|"
    bes8 ^. [ c8 ^. a8 ^. bes8 ^. ] \bar "|"
    g8 ^. [ a8 ^. f8 ^. d'8 ^. ] \bar "|"
    cis8 ^. [ bes8 ^. a8 ^. d8 ^. ] \bar "|"
    cis8 ^. [ bes8 ^. a8 ^. d8 ^. ] \bar "|"
    cis8 ^. [ bes8 ^. a8 ^. d8 ^. ] \bar "|"
    cis8 ^. [ bes8 ^. a8 ^. d8 ^. ] \bar "|"
    \break | % 186
    cis8 ^. [ a8 ^. e'8 ^. cis8 ^. ] \bar "|"
    a8 ^. [ bes8 ^. a8 ^. g8 ^. ] \bar "|"
    f8 ^. [ a8 ^. d8 ^. f,8 ^. ] \bar "|"
    e8 ^. [ d'8 ^. e,8 ^. cis'8 ^. ] \bar "|"
    <d d,>8 f,,8 ( [ g8 gis8 ) ] \bar "|"
    a4 r8 c,8 _. \bar "|"
    d8 _. [ f8 ( g8 g8 ) ] \bar "|"
    a4 r8 cis,8 _. \bar "|"
    \break | % 194
    d4 r8 fis'8 ^. _\f \bar "|"
    g8 ^. [ e8 ^. f8 ^. d8 ^. ] \bar "|"
    e8 ^. [ cis8 ^. d8 ^. bes8 ^. ] \bar "|"
    a8 ^. [ e'8 ^. g8 ^. bes,8 ^. ] \bar "|"
    a8 ^. [ e'8 ^. g8 ^. bes,8 ^. ] _\f \bar "|"
    a8 ^. [ e'8 ^. g8 ^. bes,8 ^. ] _\f \bar "|"
    a8 ^. [ e'8 ^. g8 ^. bes,8 ^. ] \bar "|"
    a4 r4 \bar "|"
    \break | % 202
    r4 cis4 \bar "|"
    d4 bes4 \bar "|"
    g4 a4 \bar "|"
    <f' a, d,>8 a8 ( [ g8 f8 ) ] \bar "|"
    e8 ^. [ g8 ( f8 e8 ) ^. ] \bar "|"
    f8 ^. [ f8 ( e8 d8 ) ^. ] \bar "|"
    cis8 ^. [ e8 ( d8 ) ( cis8 ) ] \bar "|"
    d4 <d' f, a,>4 | \barNumberCheck #210
    \time 3/8  \bar "|"
    <d f, a,>4 r8 \bar "||"
    }

PartPOneVoiceTwo =  \relative g' {
    \repeat volta 2 {
        \clef "alto" \time 1/8 \key f \major \break s8 | % 2
        \time 2/4  \bar "|"
        s2 \bar "|"
        s2 \bar "|"
        s2 \bar "|"
        s2 \bar "|"
        s2 \bar "|"
        s2 \bar "|"
        s2 \bar "|"
        s2 \bar "|"
        \break s2 \bar "|"
        s2 \bar "|"
        s2 \bar "|"
        s2 \bar "|"
        s2 \bar "|"
        s2 \bar "|"
        s2 \bar "|"
        s2 \bar "|"
        \break s2 \bar "|"
        s2 \bar "|"
        s2 \bar "|"
        s2 \bar "|"
        s2 \bar "|"
        s2 \bar "|"
        s2 \bar "|"
        s2 \bar "|"
        \break | % 26
        g8 ( [ b8 ) c8 ^. g8 ] \bar "|"
        s2 \bar "|"
        s2 \bar "|"
        s2 \bar "|"
        s2 \bar "|"
        s2 \bar "|"
        s2 \bar "|"
        \break s2 \bar "|"
        s2 \bar "|"
        s2 \bar "|"
        s2 \bar "|"
        s2 \bar "|"
        s2 \bar "|"
        s2 \bar "|"
        s2 \bar "|"
        s2 \bar "|"
        \break s2 \bar "|"
        s2 \bar "|"
        s2 \bar "|"
        s2 \bar "|"
        s2 \bar "|"
        s2 \bar "|"
        s2 \bar "|"
        s2 \bar "|"
        s2 \bar "|"
        \break s2 \bar "|"
        s2 \bar "|"
        s2 \bar "|"
        s2 \bar "|"
        s2 \bar "|"
        s2 \bar "|"
        s2 \bar "|"
        s2 \bar "|"
        \break s2 \bar "|"
        s2 \bar "|"
        s2 \bar "|"
        s2 \bar "|"
        s2 \bar "|"
        s2 \bar "|"
        s2 \bar "|"
        s2 \bar "|"
        \break s2 \bar "|"
        s2 \bar "|"
        s2 \bar "|"
        s2 \bar "|"
        s2 \bar "|"
        s2 \bar "|"
        s2 \bar "|"
        s2 \bar "|"
        \break s2 \bar "|"
        s2 \bar "|"
        s2 \bar "|"
        s2 \bar "|"
        s2 \bar "|"
        s2 \bar "|"
        s2 \bar "|"
        s2 \bar "|"
        \break s2 \bar "|"
        s2 \bar "|"
        s2 \bar "|"
        s2 \bar "|"
        s2 \bar "|"
        s2 \bar "|"
        s2 \bar "|"
        s2 \bar "|"
        \break s2 | % 92
        \time 3/8  \bar "|"
        }
    \time 2/4  \bar "|"
    s1 \bar "|"
    s2 \bar "|"
    s2 \bar "|"
    s2 \bar "|"
    s2 \bar "|"
    s2 \bar "|"
    \break s2 \bar "|"
    s2 \bar "|"
    s2 \bar "|"
    s2 \bar "|"
    s2 \bar "|"
    s2 \bar "|"
    s2 \bar "|"
    s2 \bar "|"
    \pageBreak s2 \bar "|"
    s2 \bar "|"
    s2 \bar "|"
    s2 \bar "|"
    s2 \bar "|"
    s2 \bar "|"
    s2 \bar "|"
    s2 \bar "|"
    \break s2 \bar "|"
    s2 \bar "|"
    s2 \bar "|"
    s2 \bar "|"
    s2 \bar "|"
    s2 \bar "|"
    s2 \bar "|"
    \break s2 \bar "|"
    s2 \bar "|"
    s2 \bar "|"
    s2 \bar "|"
    s2 \bar "|"
    s2 \bar "|"
    s2 \bar "|"
    s2 \bar "|"
    \break s2 \bar "|"
    s2 \bar "|"
    s2 \bar "|"
    s2 \bar "|"
    s2 \bar "|"
    s2 \bar "|"
    s2 \bar "|"
    s2 \bar "|"
    \break s2 \bar "|"
    s2 \bar "|"
    s2 \bar "|"
    s2 \bar "|"
    s1 \bar "|"
    s1 \bar "|"
    \break s2 \bar "|"
    s2 \bar "|"
    s2 \bar "|"
    s2 \bar "|"
    s2 \bar "|"
    s2 \bar "|"
    s2 \bar "|"
    s2 \bar "|"
    \break s2 \bar "|"
    s2 \bar "|"
    s2 \bar "|"
    s2 \bar "|"
    s2 \bar "|"
    s2 \bar "|"
    s2 \bar "|"
    s2 \bar "|"
    s2 \bar "|"
    \break s2 \bar "|"
    s2 \bar "|"
    s2 \bar "|"
    s2 \bar "|"
    s2 \bar "|"
    s1 \bar "|"
    \break s2 \bar "|"
    s2 \bar "|"
    s2 \bar "|"
    s2 \bar "|"
    s2 \bar "|"
    s2 \bar "|"
    s2 \bar "|"
    s2 \bar "|"
    \break s2 \bar "|"
    s2 \bar "|"
    s2 \bar "|"
    s2 \bar "|"
    s2 \bar "|"
    s2 \bar "|"
    s2 \bar "|"
    \break s2 \bar "|"
    s2 \bar "|"
    s2 \bar "|"
    s2 \bar "|"
    s2 \bar "|"
    s2 \bar "|"
    s2 \bar "|"
    s2 \bar "|"
    \break s2 \bar "|"
    s2 \bar "|"
    s2 \bar "|"
    s2 \bar "|"
    s2 \bar "|"
    s2 \bar "|"
    s2 \bar "|"
    s2 \bar "|"
    \break s2 \bar "|"
    s2 \bar "|"
    s2 \bar "|"
    s2 \bar "|"
    s2 \bar "|"
    s2 \bar "|"
    s2 \bar "|"
    s2 | \barNumberCheck #210
    \time 3/8  \bar "|"
    }


% The score definition
\score {
    <<
        
        \new StaffGroup
        <<
            \new Staff
            <<
                \set Staff.instrumentName = "Piano"
                
                \context Staff = "1" << 
                    \mergeDifferentlyDottedOn\mergeDifferentlyHeadedOn
                    \context Voice = "PartPOneVoiceOne" {  \voiceOne \PartPOneVoiceOne }
                    \context Voice = "PartPOneVoiceTwo" {  \voiceTwo \PartPOneVoiceTwo }
                    >>
                >>
            
            >>
        
        >>
    \layout {}
    % To create MIDI output, uncomment the following line:
    %  \midi {\tempo 4 = 100 }
    }

